version: "3.8"

services:
  frontend:
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=development
      # Sets the timezone of the containers OS
      - TZ=Europe/Amsterdam
      # Sets origin for csrf attacks
      - ORIGIN=http://localhost:5000
    restart: unless-stopped
    ports:
      - 3000:5050

  yarp-gateway:
    ports:
      - 5000:80
      - 4000:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  rabbitmq:
    ports:
        - 5001:5672
    volumes:
      - aicook-rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 3s
      retries: 30

  recipe-service:
    ports: 
      - 5010:5010
    depends_on:
      recipe-service.db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file:
      ./AICook.RecipeService/.env
  
  recipe-service.db:
    ports:
      - 5011:3306
    environment:
      MARIADB_USER: docker
      MARIADB_ROOT_PASSWORD: docker
      MARIADB_PASSWORD: docker
      MARIADB_DATABASE: RecipeService
    volumes:
      - aicook-recipe-service-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 3s
      retries: 30
  
  ai-worker-service:
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file:
      ./AICook.AIWorkerService/.env
  
  identity-service:
    ports:
      - 5020:5020
    depends_on:
      rabbitmq:
        condition: service_healthy
      identity-service.db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file:
      ./AICook.Identity/.env

  identity-service.db:
    ports:
      - 5021:3306
    environment:
      MARIADB_USER: docker
      MARIADB_ROOT_PASSWORD: docker
      MARIADB_PASSWORD: docker
      MARIADB_DATABASE: IdentityService
    volumes:
      - aicook-identity-service-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 3s
      retries: 30

volumes:
  aicook-rabbitmq:
  aicook-recipe-service-db:
  aicook-identity-service-db:

networks:
  default:
    name: aicook-yarp-network
    driver: bridge